set(MYKEY_UP SDLK_UP)
set(MYKEY_RIGHT SDLK_RIGHT)
set(MYKEY_DOWN SDLK_DOWN)
set(MYKEY_LEFT SDLK_LEFT)
set(MYKEY_LINEUP SDLK_LSHIFT) # X
set(MYKEY_LINERIGHT SDLK_LALT) # A
set(MYKEY_LINEDOWN SDLK_LCTRL) # B
set(MYKEY_LINELEFT SDLK_SPACE) # Y
set(MYKEY_QUIT SDLK_ESCAPE) # SELECT
set(MYKEY_START SDLK_RETURN) # START
set(MYKEY_MOD SDLK_TAB) # L
set(MYKEY_UNDO SDLK_BACKSPACE) # R
